# Generated by Django 2.2 on 2020-04-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Shows',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='nerwork',
            new_name='network',
        ),
    ]
